version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
  build:
    commands:
      - echo "Building the application..."
      - zip -r lambda.zip lambda.py AppSpec.yml
artifacts:
  files:
    - lambda.zip
